### ISSUE TITLE
Unnecessary double quotes added to PHP binary path

### ISSUE THREAD

**Issue by jamesBFS** [win32service/service-library#7]
In lib\Model\ServiceInformations.php, line 48, I don't think that the surrounding double quotes to the php binary path are necessary.

When I have installed the service on Windows Server 2016, I have manually removed the quotes to leave line 48 as follows:-
$this->datas[WIN32_INFO_PATH] = dirname(PHP_BINARY).'\php-win.exe';

I suggest this change to the code, but this is my first exploration into contributing on github, so please let me know if I should have submitted this in a different way.

**Comment by macintoshplus** [comment]
Hi @jamesBFS ,

Thank you for your feedback.

If the path to the PHP binary contains a space, you need to use the double quote to preserve the path. Otherwise, you need to use the short folder name (MS-DOS format).

If your path doesn't have any space, the double quote has no effect.

Have you a side effect cased by the double quote?

**Comment by jamesBFS** [comment]
Thank you for the prompt response.

There are double quotes added somewhere else (maybe by Windows as the
service is created), so the quotes I referenced then create double double
quotes at each end of the path. The service is created without error, but
fails to start, because it looks like two empty attributes are set, with
the correct path in between these. ie (""C:\Progam Files\PHP\php-win.exe"")

My thought is that maybe different versions of Windows handle this service
creation differently, with some that add the double quotes automatically,
and others that expect you to handle it yourself, but I only have Windows
Server 2016 to test on.

James Cecil



*Billericay Fertiliser Services Ltd*

*More than 70 years of superior service*

*T* 01245 325849

*E* ***@***.***

*W* www.bfsfertiliserservices.uk <http://www.bfs.uk.com/>

Ilgars Fertiliser Works, Willow Grove, Woodham Ferrers, Essex CM3 8RD

Registered in England number 06911560

**Comment by macintoshplus** [comment]
Can you provide this information, please:

* your service configuration (the PHP code executed to register the service, or Win32Service bundle configuration)
* PHP installation path
* PHP version
* Win32Service version

**Comment by jamesBFS** [comment]
The php to register the service is dependent on level-2\dice dependency injection container version 4.0.3 downloaded using composer. It may be that the problem I am experiencing is created by this, but I can't see where if that is the case.

From the command line, "php plugins.php PrintServiceInstall" is the installation command.

Versions of plugins.php, DiceConfigure.php and config.php are attached (with irrelevant code removed)

PHP Installation Path "C:\Program Files\PHP\v8.1.11\"
PHP version 8.1.11 NTS x64
Win32Service version 1.0.1

I did have a similar issue prior to upgrading PHP versions:-
PHP Installation Path "C:\Program Files\PHP\v7.4.26\"
PHP version 7.4.26 NTS x64
Win32Service version 0.4.2

[config.php.txt](https://github.com/win32service/service-library/files/9900689/config.php.txt)
[DiceConfigure.php.txt](https://github.com/win32service/service-library/files/9900690/DiceConfigure.php.txt)
[plugins.php.txt](https://github.com/win32service/service-library/files/9900691/plugins.php.txt)

**Comment by macintoshplus** [comment]
Hi,

When I run your code, I have this error:

```
Fatal error: Uncaught Error: Class "Dice\Dice" not found in C:\sites\DiceConfigure.php:82
Stack trace:
#0 C:\sites\plugins.php(13): BFSFertiliser\Fertiliser\DiceConfigure->getDice(Array)
#1 {main}
  thrown in C:\sites\DiceConfigure.php on line 82
```

**Comment by macintoshplus** [comment]
I can reproduce the problem.

During the service registration, the path is automatically protected by a double quote if contains space.

I write a fix quickly

**Comment by jamesBFS** [comment]
Thank you very much for both the fix and for the project as a whole.
